add recursive rule
Parquery/lexery pull request #20
Opened 2023-03-22 07:48 UTC by mpskex

You can do like 
```python
import re
from lexer import Lexer, Rule

text = 'a b(ac) c'
lexer = Lexer(rules=[Rule('a', re.compile('a\s*')),
                     Rule('b', re.compile('b\(\w+\)\s*'), next=[
                         Rule('clause', re.compile('b\(')),
                         Rule('obj', re.compile('\w+')),
                         Rule(')', re.compile('\)')),
                         ]),
                     Rule('c', re.compile('c')),
                     ])
t = lexer.lex(text)
```
It will give you 
```
[Token('a', 'a', 0, 0), Token('b', [Token('clause', 'b(', 0, 0), Token('obj', 'ac', 2, 0), Token(')', ')', 4, 0)], 5, 0), Token('c', 'c', 7, 0)]
```

2023-03-29 20:45 UTC, mristin commented
@mpskex please apologize for the delay; it's been busy lately on my side. I'll try to review the pull request till this weekend.

2023-04-11 07:44 UTC, mristin commented
@mpskex indeed, Python 3.6 is not supported by GitHub anymore. I'll try to fix the CI tonight.

2023-04-13 09:29 UTC, mristin requested changes
Thanks a lot, @mpskex ! I made only a couple of minor change suggestions related to the style of the code.

2023-04-13 09:29 UTC, mristin commented on lexery/__init__.py
> +                    pos += len(_mtch.group())
```suggestion
                another_mtch, another_t = r.match(mtch.group(), pos, 0)
                if another_mtch:
                    ret.append(another_t)
                    pos += len(another_mtch.group())
```

2023-04-13 09:29 UTC, mristin commented on lexery/__init__.py
> +                    _line = line
Please rename `_line` to `another_line`. Ditto for `_token` to `another_token`.

We use `_*` naming convention for private/protected members of a class.

2023-04-13 09:29 UTC, mristin commented
@mpskex thanks again! I fixed CI in the meanwhile. Could you please rebase your fork on the new master and have a look at my review comments?

2023-04-21 12:25 UTC, mristin approved these changes
LGTM, thanks!

2023-04-22 00:27 UTC, mpskex commented
I just reran `precommit.py` and found `pydocstyle` command was conflicting the format options. So I disabled `D203`, `D204` and `D212` in `pydocstyle` check. Now it should be good.

2023-04-23 04:10 UTC, mristin commented
@mpskex the format still seems to be off? Could you please run `precommit.py --overwrite`, and commit?

2023-04-23 12:24 UTC, mpskex commented
> I just reran `precommit.py` and found `pydocstyle` command was conflicting the format options. So I disabled `D203`, `D204` and `D212` in `pydocstyle` check. Now it should be good.

This is reverted.

2023-04-23 12:47 UTC, mpskex commented
> @mpskex the format still seems to be off? Could you please run `precommit.py --overwrite`, and commit?

Sry for that, it must be the wrong yapf version i installed. The format should be ok now.

2023-05-23 21:18 UTC, merged

2023-05-23 21:19 UTC, mristin commented
@mpskex thanks a lot! I'm just about to release a new minor version.

Please apologize for the delay. I was out-of-town with my family on holidays, and then had to deal with a backlog after coming back.

2023-05-23 21:31 UTC, mristin commented
P.S. @mpskex if you haven't done so, please consider starring the project to give it some visibility.